---
- name: Make host group for targeted vm dns name
  hosts: localhost
  gather_facts: false
  become: true
  
  tasks:
    - name: manaul instll of the repo
      ansible.builtin.shell:
        cmd: ansible-galaxy collection install git+https://github.com/cloudapps-idey/message_collection.git
    - name: list collections
      ansible.builtin.shell:
        cmd: ansible-galaxy collection list
      register: collection_list

    - name: display collection_list
      ansible.builtin.debug:
        msg: "{{ collection_list }}"
        
    - name: Use the diplay_message role
      import_collection:
        name: samplenamespace.message_collection

